---
# Variables pour l'installation Docker
docker_compose_version: "v2.24.1"
docker_users:
  - "{{ ansible_user }}"

# Variables syst√®me
system_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - software-properties-common

# Dossiers de travail
work_directories:
  - /opt/applications
  - /opt/data
  - /opt/logs
